name: Release

on:
  push:
    tags: ["v*"]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  build:
    needs: ["create-release"]
    strategy:
      fail-fast: false
      matrix:
        # https://doc.rust-lang.org/rustc/platform-support.html
        # We build all the tier-1 targets at the link above. Should users need a less common target, they can always build it themselves.
        include:
          - label: 64-bit-windows
            target: x86_64-pc-windows-msvc
            runs-on: windows-latest
          - label: 32-bit-windows
            target: i686-pc-windows-msvc
            runs-on: windows-latest
          - label: 64-bit-linux
            target: x86_64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - label: 32-bit-linux
            target: i686-unknown-linux-gnu
            runs-on: ubuntu-latest
          - label: arm64-linux
            target: aarch64-unknown-linux-gnu
            runs-on: ubuntu-latest
          - label: 64-bit-macos
            target: x86_64-apple-darwin
            runs-on: macos-latest

    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          profile: minimal

      - name: Build Release
        run: cargo build --release --locked --verbose
        env:
          CARGO_TARGET_DIR: output

      - name: Create Release Archive
        shell: bash
        run: |
          mkdir staging

          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cp "output/release/fsyaml.exe" staging/
            cd staging
            7z a ../release.zip *
          else
            cp "output/release/fsyaml" staging/
            cd staging
            zip ../release.zip *
          fi

      - name: Upload Archive to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: release.zip
          asset_name: fsyaml-${{ github.ref_name }}-${{ matrix.label }}.zip
          asset_content_type: application/octet-stream

      - name: Upload Archive as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: fsyaml-${{ github.ref_name }}-${{ matrix.label }}.zip
          path: release.zip
